core/blog/urls.py
# Django Imports
from django.urls import path

# Local Imports
from . import views

app_name = 'blog'
urlpatterns = [
    path('list/', views.BlogListView.as_view(), name='blog-list'),
    path('detail/<int:pk>/', views.BlogDetailView.as_view(), name='blog-detail'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/website/urls.py
# Django Imports
from django.urls import path

# Local Imports
from . import views

app_name = 'website'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('about-us/', views.AboutUsPageView.as_view(), name='about-us'),
    path('contact-us/', views.ContactUsPageView.as_view(), name='contact-us'),
]

core/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html {% if request.LANGUAGE_CODE == 'fa' %}lang="fa"{% else %}lang="en"{% endif %} dir="{% if request.LANGUAGE_CODE == 'fa' %}rtl{% else %}ltr{% endif %}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">

    <title>{% block page_title %}{% endblock %}</title>


    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/font-awesome.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/templatemo-hexashop.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/owl-carousel.css' %}">

    <link rel="stylesheet" href="{% static 'assets/css/lightbox.css' %}">
    {% if request.LANGUAGE_CODE == 'fa' %}
        <link rel="stylesheet" href="{% static 'assets/css/rtl.css' %}">
    {% endif %} 
    <style>
.slider {
    position: relative;
    width: 100%;
    height: 250px;
    margin: 20px auto;
    overflow: hidden;
    border-radius: 10px;
}

.slide {
    position: absolute;
    inset: 0;
    opacity: 0;
    transition: opacity 0.5s ease;
}

.slide.active {
    opacity: 1;
}

.slide img {
    width: 100%;
    height: 100%;
    object-fit: cover;
}

/* --- دکمه‌های Prev و Next --- */

.slider button {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    background: rgba(0,0,0,0.5);
    color: white;
    border: none;
    padding: 12px 18px;
    font-size: 22px;
    cursor: pointer;
    border-radius: 50%;
    transition: 0.3s;
}

.slider button:hover {
    background: rgba(0,0,0,0.8);
}

.prev {
    left: 10px;
}

.next {
    right: 10px;
}

</style>

    {% block extra_css %}{% endblock %}
    </head>
    <body>
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->
    
    
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo" {% if request.LANGUAGE_CODE == 'fa' %}style="float: right;"{% endif %}>
                            <img src="{% static 'assets/images/logo-fahimweb.png' %}">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav" {% if request.LANGUAGE_CODE == 'fa' %}style="float: left;"{% endif %}>
                            <li><a href="{% url 'website:home' %}" class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">{% trans 'خانه' %}</a></li>
                            <li><a href="{% url 'blog:blog-list' %}">{% trans 'بلاگ ها' %}</a></li>
                            
                            <li><a href="{% url 'website:about-us' %}" class="{% if request.resolver_match.url_name == 'about-us' %}active{% endif %}">{% trans 'درباره ما' %}</a></li>
                            <li><a href="{% url 'website:contact-us' %}" class="{% if request.resolver_match.url_name == 'contact-us' %}active{% endif %}">{% trans 'ارتباط با ما' %}</a></li>
                        
                            {% if request.LANGUAGE_CODE == 'en'%}                         
                            <li><a href="/fa/">{% trans 'Persian' %}</a></li>  
                            {% else %}
                            <li><a href="/en/">{% trans 'انگلیسی' %}</a></li>  
                            {% endif %}                           
                        </ul>        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->
    {% block content %}{% endblock %}

    <!-- ***** Footer Start ***** -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="first-item">
                        <div class="logo">
                            <img src="{% static 'assets/images/white-logo.png' %}" alt="hexashop ecommerce templatemo">
                        </div>
                        <ul>
                            <li><a href="#">{{ contact.address }}</a></li>
                            <li><a href="#">{{ contact.email }}</a></li>
                            <li><a href="#">{{ contact.phone_number }}</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <h4>{% trans 'بلاگ ها' %} &amp; {% trans 'دسته بندی های پر بازدید' %}</h4>
                    <ul>
                        <li><a href="#">{% trans 'در برنامه نویسی' %}</a></li>
                        <li><a href="#">{% trans 'در اقتصاد' %}</a></li>
                        <li><a href="#">{% trans 'در سیاست' %}</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>{% trans 'لینک های ضروری' %}</h4>
                    <ul>
                        <li><a href="{% url 'website:home' %}">{% trans 'خانه' %}</a></li>
                        <li><a href="{% url 'website:about-us' %}">{% trans 'درباره ما' %}</a></li>
                        <li><a href="#">{% trans 'کمک' %}</a></li>
                        <li><a href="{% url 'website:contact-us' %}">{% trans 'ارتباط با ما' %}</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>{% trans 'کمک' %} &amp; {% trans 'اطلاعات' %}</h4>
                    <ul>
                        <li><a href="#">{% trans 'کمک' %}</a></li>
                        <li><a href="#">{% trans 'سوالات متداول' %}</a></li>
                        <li><a href="#">{% trans 'ثبت نام' %}</a></li>
                        <li><a href="#">{% trans 'ورود' %}</a></li>
                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="under-footer">
                        <p>Copyright © 2022 HexaShop Co., Ltd. All Rights Reserved. 
                        
                        <br>{% trans 'با مدیریت' %}: <a href="https://github.com/FahimReza1386/" target="_parent" title="free css templates">{{ contact.owner_name }}</a></p>
                        <ul>
                            <li><a href="{{ contact.facebook_link }}"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="{{ contact.twitter_link }}"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="{{ contact.linkedin_link }}"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="{{ contact.instagram_link }}"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    

    <!-- jQuery -->
    <script src="{% static 'assets/js/jquery-2.1.0.min.js' %}"></script>

    <!-- Bootstrap -->
    <script src="{% static 'assets/js/popper.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>

    <!-- Plugins -->
    <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
    <script src="{% static 'assets/js/accordions.js' %}"></script>
    <script src="{% static 'assets/js/datepicker.js' %}"></script>
    <script src="{% static 'assets/js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'assets/js/waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'assets/js/imgfix.min.js' %}"></script> 
    <script src="{% static 'assets/js/slick.js' %}"></script> 
    <script src="{% static 'assets/js/lightbox.js' %}"></script> 
    <script src="{% static 'assets/js/isotope.js' %}"></script> 
    
    <!-- Global Init -->
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>


    <script>

        $(function() {
            var selectedClass = "";
            $("p").click(function(){
            selectedClass = $(this).attr("data-rel");
            $("#portfolio").fadeTo(50, 0.1);
                $("#portfolio div").not("."+selectedClass).fadeOut();
            setTimeout(function() {
              $("."+selectedClass).fadeIn();
              $("#portfolio").fadeTo(50, 1);
            }, 500);
                
            });
        });

    </script>
    <script>
document.querySelectorAll('.slider').forEach(slider => {
    let index = 0;
    const slides = slider.querySelectorAll('.slide');
    const prevBtn = slider.querySelector('.prev');
    const nextBtn = slider.querySelector('.next');

    function showSlide(i) {
        slides.forEach(s => s.classList.remove('active'));
        slides[i].classList.add('active');
    }

    nextBtn.addEventListener('click', () => {
        index = (index + 1) % slides.length;
        showSlide(index);
    });

    prevBtn.addEventListener('click', () => {
        index = (index - 1 + slides.length) % slides.length;
        showSlide(index);
    });
});
</script>
{% include 'messages.html' %}
{% block extra_js %}{% endblock %}
  </body>
</html>

core/templates/messages.html
{% if messages %}

    {% for message in messages %}
    
        <script>
            Toastify({
                text:`{{ message|safe }}`,
                className: `{{ message.tags }}`,
                style: {
                    background:"green",
                },  
            }).showToast();
        </script>
    
    {% endfor %}

{% endif %}

{% if form.errors %}

    <div class="alert alert-error" style="font-family: 'Vazir',sans-serif ;">
        <ul>
            {% for field in form%}
                {% if field.errors %}
                    {% for error in field.errors %}
                    <script>
                        Toastify({
                            text:`{{ error|escape }}`,
                            className: `error`,
                            style: {
                                background : 'red',
                            }
                        }).showToast();
                    </script>
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </ul>
        {% if field.non_field_errors %}
            <script>
                Toastify({
                    text:`{{ form.non_field_errors.as_text }}`,
                    className: `error`,
                    style:{
                        background:"red",
                    }

                }).showToast();
            </script>
        {% endif %}
    </div>
{% endif %}